version: "3"
services:
  app:
    build: ./app
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
  api:
    build: ./api
    tty: true
    volumes:
      - ./api:/go/src/api
