name: test/deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./app
    - run: npm test -- -u
      working-directory: ./app
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Vercel Deploy
      uses: amondnet/vercel-action@v20.0.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} 
        vercel-args: '--prod' 
        vercel-org-id: ${{ secrets.ORG_ID}}  
        vercel-project-id: ${{ secrets.PROJECT_ID}} 
        working-directory: ./
